# Generated by Django 6.0.7 on 2026-07-17 04:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


STATUS_MAP = {
    'present': 'P',
    'absent': 'A',
    'leave': 'CL',
    'half_day': 'HD',
}


def migrate_attendance_records(apps, schema_editor):
    """Copy legacy AttendanceRecord rows into the new Attendance model before drop."""
    AttendanceRecord = apps.get_model('attendance', 'AttendanceRecord')
    Attendance = apps.get_model('attendance', 'Attendance')
    # Clear Meta.ordering — legacy AttendanceRecord ordered by employee__employee_id
    # which no longer exists on Employee after Sprint 5 renames.
    for record in AttendanceRecord.objects.order_by('pk').iterator():
        Attendance.objects.update_or_create(
            employee_id=record.employee_id,
            attendance_date=record.date,
            defaults={
                'status': STATUS_MAP.get(record.status, 'P'),
                'check_in': record.check_in,
                'check_out': record.check_out,
                'remarks': record.notes or '',
                'worked_hours': Decimal('0.00'),
                'overtime_hours': Decimal('0.00'),
                'late_minutes': 0,
                'early_exit_minutes': 0,
                'approved': False,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('company', '0006_organisation_structure'),
        ('employee', '0006_alter_salarystructure_hra_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('processed', 'Processed')], default='open', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_periods', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_period_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_period_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'company__company_name'],
                'permissions': [('reopen_attendanceperiod', 'Can reopen locked attendance period')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('present_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('absent_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('weekly_off_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('holiday_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('half_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('lop_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_monthlysummary_created_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_monthly_summaries', to='employee.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_monthlysummary_updated_records', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='attendance.attendanceperiod')),
            ],
            options={
                'verbose_name_plural': 'attendance monthly summaries',
                'ordering': ['-period__year', '-period__month', 'employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('holiday_date', models.DateField()),
                ('holiday_name', models.CharField(max_length=200)),
                ('holiday_type', models.CharField(choices=[('national', 'National'), ('festival', 'Festival'), ('optional', 'Optional'), ('company', 'Company'), ('regional', 'Regional')], default='national', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_holiday_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_holiday_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-holiday_date', 'holiday_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('shift_code', models.CharField(max_length=20)),
                ('shift_name', models.CharField(max_length=100)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=60)),
                ('grace_in_minutes', models.PositiveIntegerField(default=10)),
                ('grace_out_minutes', models.PositiveIntegerField(default=10)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5)),
                ('full_day_hours', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('is_night_shift', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_shift_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_shift_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__company_name', 'shift_code'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Holiday'), ('WO', 'Weekly Off'), ('CL', 'Casual Leave'), ('SL', 'Sick Leave'), ('EL', 'Earned Leave'), ('LOP', 'Loss of Pay'), ('HD', 'Half Day'), ('OD', 'On Duty')], default='P', max_length=5)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_exit_minutes', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_created_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='employee.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_updated_records', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_days', to='attendance.shift')),
            ],
            options={
                'verbose_name_plural': 'attendance',
                'ordering': ['-attendance_date', 'employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_shiftassignment_created_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employee.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.shift')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_shiftassignment_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee__employee_code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_weeklyoff_created_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_offs', to='employee.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_weeklyoff_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'weekly off',
                'verbose_name_plural': 'weekly offs',
                'ordering': ['employee__employee_code', 'weekday', 'effective_from'],
            },
        ),
        migrations.RunPython(migrate_attendance_records, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.AddConstraint(
            model_name='attendanceperiod',
            constraint=models.UniqueConstraint(fields=('company', 'month', 'year'), name='uniq_attendance_period_company_month_year'),
        ),
        migrations.AddConstraint(
            model_name='attendancemonthlysummary',
            constraint=models.UniqueConstraint(fields=('employee', 'period'), name='uniq_attendance_monthly_summary_employee_period'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('company', 'holiday_date', 'holiday_name'), name='uniq_holiday_company_date_name'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('company', 'shift_code'), name='uniq_shift_company_code'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'attendance_date'), name='uniq_attendance_employee_date'),
        ),
    ]
