# Generated by Django 6.0.7 on 2026-07-17 04:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employment_type_and_document_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='hra_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='HRA as percentage of basic salary.', max_digits=5),
        ),
    ]
