# Generated by Django 6.0.7 on 2026-07-17 05:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_organisation_structure'),
        ('employee', '0006_alter_salarystructure_hra_percent'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-pay_period__year', '-pay_period__month', 'employee__employee_code']},
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('component_code', models.CharField(max_length=30)),
                ('component_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution')], max_length=30)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('formula', 'Formula')], default='fixed', max_length=20)),
                ('formula', models.CharField(blank=True, max_length=500)),
                ('taxable', models.BooleanField(default=True)),
                ('pf_applicable', models.BooleanField(default=False)),
                ('esi_applicable', models.BooleanField(default=False)),
                ('include_in_ctc', models.BooleanField(default=True)),
                ('include_in_gross', models.BooleanField(default=True)),
                ('rounding_rule', models.CharField(choices=[('none', 'None'), ('nearest', 'Nearest Rupee'), ('round_up', 'Round Up'), ('round_down', 'Round Down')], default='nearest', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_salarycomponent_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_salarycomponent_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__company_name', 'display_order', 'component_code'],
                'permissions': [('export_salarycomponent', 'Can export salary component register')],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_salary_structures', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_salarystructure_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_salarystructure_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['company__company_name', 'name'],
                'permissions': [('export_salarystructure', 'Can export salary structure register')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null means currently active.', null=True)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ctc', models.DecimalField(decimal_places=2, help_text='Annual CTC; leave 0 to auto-calculate from monthly figures.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_salaryassignment_created_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignments', to='employee.employee')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_salaryassignment_updated_records', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='payroll.salarystructure')),
            ],
            options={
                'verbose_name': 'Employee Salary Assignment',
                'verbose_name_plural': 'Employee Salary Assignments',
                'ordering': ['-effective_from', '-id'],
                'permissions': [('export_employeesalaryassignment', 'Can export employee salary register')],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('formula', 'Formula')], help_text='Leave blank to use the component default.', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount when calculation type is Fixed.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('percent', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage value when calculation type is Percentage.', max_digits=8, null=True)),
                ('formula_override', models.CharField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_lines', to='payroll.salarycomponent')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.salarystructure')),
            ],
            options={
                'verbose_name': 'Salary Structure Line',
                'verbose_name_plural': 'Salary Structure Lines',
                'ordering': ['display_order', 'component__component_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='salarycomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'component_code'), name='uniq_salarycomponent_company_code_alive'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company', 'code'), name='uniq_payroll_salarystructure_company_code_alive'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureline',
            constraint=models.UniqueConstraint(fields=('structure', 'component'), name='uniq_structure_line_component'),
        ),
    ]
