# Generated by Django 6.0.7 on 2026-07-17 05:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_organisation_structure'),
        ('employee', '0006_alter_salarystructure_hra_percent'),
        ('payroll', '0002_salary_structure_sprint7'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_period_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_period_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-year', '-month', 'company__company_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('absent_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lop_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ctc_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Optional CTC snapshot at calculation time.', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_results', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Payroll Result',
                'verbose_name_plural': 'Payroll Results',
                'ordering': ['employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollResultComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_code', models.CharField(max_length=30)),
                ('component_name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('calculation_detail', models.JSONField(blank=True, default=dict, help_text='Formula inputs, rates, or other calculation metadata.')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.payrollresult')),
            ],
            options={
                'verbose_name': 'Payroll Result Component',
                'verbose_name_plural': 'Payroll Result Components',
                'ordering': ['component_type', 'component_code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField(default=1, help_text='Version number within the period (1, 2, …).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-created_at', '-run_number'],
            },
        ),
        migrations.AddField(
            model_name='payrollresult',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='PayrollAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payroll.payrollperiod')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Audit Log',
                'verbose_name_plural': 'Payroll Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('company', 'month', 'year'), name='uniq_payroll_period_company_month_year'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('period', 'run_number'), name='uniq_payroll_run_period_number'),
        ),
        migrations.AddConstraint(
            model_name='payrollresult',
            constraint=models.UniqueConstraint(fields=('run', 'employee'), name='uniq_payroll_result_run_employee'),
        ),
    ]
