# Generated by Django 6.0.7 on 2026-07-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_calculation_sprint82'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrun',
            options={'ordering': ['-created_at', '-run_number'], 'permissions': [('review_payrollrun', 'Can review payroll run'), ('approve_payrollrun', 'Can approve payroll run'), ('lock_payrollrun', 'Can lock payroll run')], 'verbose_name': 'Payroll Run', 'verbose_name_plural': 'Payroll Runs'},
        ),
    ]
