# Generated by Django 6.0.7 on 2026-07-17 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_esi_compliance_sprint92'),
        ('payroll', '0006_payrollrun_pf_rule_set_sprint91'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='esi_rule_set',
            field=models.ForeignKey(blank=True, help_text='ESI rule set snapshotted at calculation time (immutable historical rates).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='compliance.esiruleset'),
        ),
    ]
