# Generated by Django 6.0.7 on 2026-07-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_pt_compliance_sprint93'),
        ('payroll', '0007_esi_compliance_sprint92'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='pt_rule_set',
            field=models.ForeignKey(blank=True, help_text='Optional primary PT rule set snapshotted at calculation time (e.g. company AP seed). Per-employee jurisdiction is on PayrollPTResult.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='compliance.professionaltaxruleset'),
        ),
    ]
