# Generated by Django 6.0.7 on 2026-07-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_tds_compliance_sprint94'),
        ('payroll', '0008_pt_compliance_sprint93'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='tds_rule_set',
            field=models.ForeignKey(blank=True, help_text='Optional primary TDS / income-tax rule snapshotted at calculation time (typically NEW-regime seed for the FY). Per-employee regime is on PayrollTDSResult.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='compliance.financialyeartaxrule'),
        ),
    ]
