# Generated by Django 6.0.7 on 2026-07-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('pan', models.CharField(blank=True, max_length=10, verbose_name='PAN')),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('tan', models.CharField(blank=True, max_length=10, verbose_name='TAN')),
                ('pf_number', models.CharField(blank=True, max_length=50, verbose_name='PF Number')),
                ('esi_number', models.CharField(blank=True, max_length=50, verbose_name='ESI Number')),
                ('professional_tax_registration', models.CharField(blank=True, max_length=50, verbose_name='Professional Tax Registration')),
                ('labour_licence', models.CharField(blank=True, max_length=50, verbose_name='Labour Licence')),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10, verbose_name='PIN Code')),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='company/logos/')),
                ('bank_details', models.TextField(blank=True, help_text='Bank name, account number, IFSC, branch, etc.', verbose_name='Bank Details')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
    ]
