# Generated by Django 6.0.7 on 2026-07-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='esi_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pf_number',
        ),
        migrations.AddField(
            model_name='company',
            name='epf_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='EPF Code'),
        ),
        migrations.AddField(
            model_name='company',
            name='esi_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='ESI Code'),
        ),
    ]
