# Generated by Django 6.0.7 on 2026-07-17 08:21

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_epf_compliance_sprint91'),
        ('employee', '0006_alter_salarystructure_hra_percent'),
        ('payroll', '0006_payrollrun_pf_rule_set_sprint91'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESIRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='India ESI', max_length=100)),
                ('code', models.CharField(help_text='Stable identifier snapshotted on payroll results (e.g. IN-ESI-2024).', max_length=30, unique=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Inclusive end date. Null means open-ended.', null=True)),
                ('eligibility_wage_limit', models.DecimalField(decimal_places=2, default=Decimal('21000.00'), help_text='Monthly ESI wage ceiling for first-time eligibility in a contribution period.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0075'), help_text='Employee ESI rate as a fraction (0.0075 = 0.75%).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('employer_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0325'), help_text='Employer ESI rate as a fraction (0.0325 = 3.25%).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('daily_wage_exemption_limit', models.DecimalField(decimal_places=2, default=Decimal('176.00'), help_text='Avg daily wage at/below this amount → employee share exempt (employer still due).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rounding_method', models.CharField(choices=[('HALF_UP', 'Round half up (2 dp)'), ('NEAREST_RUPEE', 'Nearest rupee')], default='HALF_UP', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ESI Rule Set',
                'verbose_name_plural': 'ESI Rule Sets',
                'ordering': ['-effective_from', 'code'],
                'permissions': [('export_esiregister', 'Can export ESI registers'), ('export_esicontribution', 'Can export ESI contribution data')],
            },
        ),
        migrations.CreateModel(
            name='PayrollESIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_version', models.CharField(blank=True, help_text='Denormalised ESIRuleSet.code at calculation time.', max_length=30)),
                ('esi_wages', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('employee_esi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('employer_esi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_eligible', models.BooleanField(default=False)),
                ('above_wage_limit', models.BooleanField(default=False, help_text='True when ESI wages exceeded eligibility_wage_limit for this period.')),
                ('continuity_applied', models.BooleanField(default=False, help_text='True when eligibility continued due to contribution-period continuity.')),
                ('daily_wage_exemption', models.BooleanField(default=False, help_text='True when employee share was exempted due to daily wage limit.')),
                ('missing_ip_number', models.BooleanField(default=False, help_text='True when employee was ESI-applicable but IP number was missing.')),
                ('eligibility_notes', models.TextField(blank=True)),
                ('calculation_detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esi_result', to='payroll.payrollresult')),
                ('rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_esi_results', to='compliance.esiruleset')),
            ],
            options={
                'verbose_name': 'Payroll ESI Result',
                'verbose_name_plural': 'Payroll ESI Results',
                'ordering': ['payroll_result_id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeESIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_number', models.CharField(blank=True, help_text='ESI Insurance Number (IP). Typically 10 digits; spaces allowed.', max_length=17, validators=[apps.common.validators.validate_esi_ip])),
                ('joining_esi_date', models.DateField(blank=True, null=True)),
                ('exit_esi_date', models.DateField(blank=True, null=True)),
                ('is_esi_applicable', models.BooleanField(default=True)),
                ('is_daily_wage_worker', models.BooleanField(default=False, help_text='When set, average daily wage uses payable/working days for exemption checks.')),
                ('covered_period_start', models.DateField(blank=True, help_text='Start date of the ESI contribution period in which this employee was first covered. Used for continuity: once covered, remain covered until period end even if wages exceed the eligibility ceiling (unless exited).', null=True)),
                ('covered_period_end', models.DateField(blank=True, help_text='End date of the contribution period matching covered_period_start.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esi_profile', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee ESI Profile',
                'verbose_name_plural': 'Employee ESI Profiles',
                'ordering': ['employee__employee_code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ip_number', ''), _negated=True), fields=('ip_number',), name='uniq_employee_esi_ip_number_nonblank')],
            },
        ),
    ]
