# Generated by Django 6.0.7 on 2026-07-17 08:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_esi_compliance_sprint92'),
        ('employee', '0006_alter_salarystructure_hra_percent'),
        ('payroll', '0007_esi_compliance_sprint92'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTaxRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(db_index=True, help_text='ISO-like state code for PT jurisdiction (e.g. AP, TS, KA).', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Inclusive end date. Null means open-ended.', null=True)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('HALF_YEARLY', 'Half-yearly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('special_month', models.PositiveSmallIntegerField(blank=True, help_text='Calendar month (1–12) with alternate slab amounts (e.g. 2 = February for AP).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Tax Rule Set',
                'verbose_name_plural': 'Professional Tax Rule Sets',
                'ordering': ['state_code', '-effective_from'],
                'permissions': [('export_ptregister', 'Can export PT registers'), ('export_ptchallan', 'Can export PT challan / return data')],
            },
        ),
        migrations.CreateModel(
            name='EmployeePTProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(blank=True, help_text='PT jurisdiction / work state (e.g. AP). Required when is_applicable.', max_length=10)),
                ('is_applicable', models.BooleanField(default=True)),
                ('exemption_type', models.CharField(blank=True, choices=[('', 'None'), ('SENIOR_CITIZEN', 'Senior citizen'), ('DISABLED', 'Differently abled'), ('OTHER', 'Other / manual exemption')], default='', max_length=30)),
                ('exemption_reason', models.CharField(blank=True, max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, help_text='Inclusive end of this jurisdiction profile. Null = open-ended.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pt_profile', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee PT Profile',
                'verbose_name_plural': 'Employee PT Profiles',
                'ordering': ['employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('pt_wages', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('exemption_reason', models.CharField(blank=True, max_length=255)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pt_result', to='payroll.payrollresult')),
                ('rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_pt_results', to='compliance.professionaltaxruleset')),
            ],
            options={
                'verbose_name': 'Payroll PT Result',
                'verbose_name_plural': 'Payroll PT Results',
                'ordering': ['payroll_result_id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_from', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Inclusive lower bound of monthly PT wages.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive upper bound. Null = no upper limit.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('special_month_tax_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Tax in the rule set special_month (defaults to tax_amount when null).', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sequence', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='compliance.professionaltaxruleset')),
            ],
            options={
                'verbose_name': 'Professional Tax Slab',
                'verbose_name_plural': 'Professional Tax Slabs',
                'ordering': ['rule_set_id', 'sequence', 'salary_from'],
            },
        ),
    ]
