# Generated by Django 6.0.7 on 2026-07-17 11:52

import apps.common.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_pt_compliance_sprint93'),
        ('employee', '0006_alter_salarystructure_hra_percent'),
        ('payroll', '0008_pt_compliance_sprint93'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYearTaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(db_index=True, help_text='Indian FY label, e.g. 2024-25.', max_length=9)),
                ('tax_regime', models.CharField(choices=[('OLD', 'Old regime'), ('NEW', 'New regime')], max_length=10)),
                ('code', models.CharField(help_text='Stable identifier snapshotted on payroll TDS results.', max_length=40, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Inclusive end date. Null means open-ended.', null=True)),
                ('standard_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rebate_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Section 87A: taxable income at/below this → full rebate of tax (before cess).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cess_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0400'), help_text='Health & Education Cess as a fraction (0.04 = 4%).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('surcharge_rules', models.JSONField(blank=True, default=list, help_text='Ordered list of {"income_from","income_to"|null,"rate"} bands. Rates are fractions (0.10 = 10%). Engine loads from DB only.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Year Tax Rule',
                'verbose_name_plural': 'Financial Year Tax Rules',
                'ordering': ['-financial_year', 'tax_regime', '-effective_from'],
                'permissions': [('export_tdsregister', 'Can export TDS registers'), ('export_form16', 'Can export Form 16 preparation data')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_regime', models.CharField(choices=[('OLD', 'Old regime'), ('NEW', 'New regime')], default='NEW', max_length=10)),
                ('pan_number', models.CharField(blank=True, max_length=10, validators=[apps.common.validators.validate_pan])),
                ('tax_residency', models.CharField(choices=[('RESIDENT', 'Resident'), ('NRI', 'Non-resident'), ('RNOR', 'Resident but not ordinarily resident')], default='RESIDENT', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('is_tds_applicable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee Tax Profile',
                'verbose_name_plural': 'Employee Tax Profiles',
                'ordering': ['employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTDSResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=9)),
                ('tax_regime', models.CharField(blank=True, max_length=10)),
                ('taxable_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Projected annual taxable income used for slab calculation.', max_digits=14)),
                ('annual_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total annual tax liability including surcharge and cess.', max_digits=14)),
                ('monthly_tds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_before_cess', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('surcharge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cess', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rebate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('relief', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reserved for u/s 89 relief; default zero.', max_digits=14)),
                ('previous_tds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='YTD payroll TDS + previous employer TDS already recovered.', max_digits=14)),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tds_result', to='payroll.payrollresult')),
                ('rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_tds_results', to='compliance.financialyeartaxrule')),
            ],
            options={
                'verbose_name': 'Payroll TDS Result',
                'verbose_name_plural': 'Payroll TDS Results',
                'ordering': ['payroll_result_id'],
            },
        ),
        migrations.CreateModel(
            name='PreviousEmployerIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pf_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_employer_incomes', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Previous Employer Income',
                'verbose_name_plural': 'Previous Employer Incomes',
                'ordering': ['-financial_year', 'employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(db_index=True, max_length=9)),
                ('regime', models.CharField(choices=[('OLD', 'Old regime'), ('NEW', 'New regime')], max_length=10)),
                ('declared_amounts', models.JSONField(blank=True, default=dict, help_text='Flexible map of deduction codes → amounts (e.g. {"80C": "150000"}).')),
                ('section_80c', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('section_80d', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('housing_loan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest on housing loan (e.g. u/s 24).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Claimed HRA exemption amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Tax Declaration',
                'verbose_name_plural': 'Tax Declarations',
                'ordering': ['-financial_year', 'employee__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=9)),
                ('category', models.CharField(choices=[('80C', 'Section 80C'), ('80D', 'Section 80D'), ('80CCD', 'Section 80CCD'), ('HRA', 'HRA exemption'), ('HOUSING_LOAN', 'Housing loan interest'), ('OTHER', 'Other deduction')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='compliance/investment_proofs/')),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_proofs', to='employee.employee')),
                ('declaration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='compliance.taxdeclaration')),
            ],
            options={
                'verbose_name': 'Investment Proof',
                'verbose_name_plural': 'Investment Proofs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_from', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Inclusive lower bound of annual taxable income.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('income_to', models.DecimalField(blank=True, decimal_places=2, help_text='Inclusive upper bound. Null = no upper limit.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tax rate as a fraction (0.05 = 5%).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('sequence', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='compliance.financialyeartaxrule')),
            ],
            options={
                'verbose_name': 'Tax Slab',
                'verbose_name_plural': 'Tax Slabs',
                'ordering': ['rule_id', 'sequence', 'income_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxdeclaration',
            constraint=models.UniqueConstraint(fields=('employee', 'financial_year'), name='uniq_tax_declaration_employee_fy'),
        ),
    ]
